//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ngRoute
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public long ID { get; set; }
        public string LogType { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public string SourceEvent { get; set; }
        public string LogMessage { get; set; }
        public Nullable<System.Guid> SyncID { get; set; }
    }
}
