//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ngRoute
{
    using System;
    using System.Collections.Generic;
    
    public partial class vWorkItem
    {
        public Nullable<System.DateTime> Activated_Date { get; set; }
        public string ActivatedBy { get; set; }
        public string Application { get; set; }
        public string AreaPath { get; set; }
        public string AssignedTo { get; set; }
        public Nullable<System.DateTime> Closed_Date { get; set; }
        public string ClosedBy { get; set; }
        public Nullable<decimal> Completed_Work { get; set; }
        public Nullable<decimal> Completed_Work_Agg { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Due_Date { get; set; }
        public string Found_In { get; set; }
        public Nullable<long> ID { get; set; }
        public long Index { get; set; }
        public int IsParent { get; set; }
        public string Iteration_Path { get; set; }
        public string Mode { get; set; }
        public Nullable<decimal> Original_Estimate { get; set; }
        public Nullable<decimal> Original_Estimate_Agg { get; set; }
        public string OwnedBy { get; set; }
        public Nullable<long> PID { get; set; }
        public Nullable<int> Priority { get; set; }
        public string Project { get; set; }
        public string Reason { get; set; }
        public Nullable<decimal> Remaining_Work { get; set; }
        public Nullable<decimal> Remaining_Work_Agg { get; set; }
        public Nullable<System.DateTime> Resolved_Date { get; set; }
        public string ResolvedBy { get; set; }
        public string Severity { get; set; }
        public string State { get; set; }
        public Nullable<int> Story_Points { get; set; }
        public string Tags { get; set; }
        public string Title { get; set; }
        public string Type { get; set; }
        public string TreePath { get; set; }
        public string Url { get; set; }
        public Nullable<int> udf_ConnectionID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
