//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ngRoute
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkItemUpdate
    {
        public long ID { get; set; }
        public Nullable<int> ConnectionID { get; set; }
        public Nullable<long> WorkItemID { get; set; }
        public Nullable<System.DateTime> RevisedDate { get; set; }
        public string RevisedBy { get; set; }
        public Nullable<int> RevNumber { get; set; }
        public string FieldName { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
    }
}
