//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ngRoute
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkItem
    {
        public long ID { get; set; }
        public Nullable<long> WIID { get; set; }
        public string WorkItemType { get; set; }
        public string Title { get; set; }
        public string State { get; set; }
        public string Reason { get; set; }
        public string AreaPath { get; set; }
        public string IterationPath { get; set; }
        public string Severity { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> StoryPoints { get; set; }
        public Nullable<decimal> OriginalEstimate { get; set; }
        public Nullable<decimal> CompletedWork { get; set; }
        public Nullable<decimal> RemainingWork { get; set; }
        public string CreatedBy { get; set; }
        public string AssignedTo { get; set; }
        public string ActivatedBy { get; set; }
        public string ResolvedBy { get; set; }
        public string ClosedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ActivatedDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> ResolvedDate { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public string Tags { get; set; }
        public string Activity { get; set; }
        public Nullable<System.DateTime> ChangedDate { get; set; }
        public Nullable<short> udf_ParentLevel { get; set; }
        public Nullable<long> udf_PWIID { get; set; }
        public Nullable<decimal> udf_OriginalEstimateAgg { get; set; }
        public Nullable<decimal> udf_CompletedWorkAgg { get; set; }
        public Nullable<decimal> udf_RemainingWorkAgg { get; set; }
        public string udf_AppName { get; set; }
        public string udf_Mode { get; set; }
        public string udf_FoundIn { get; set; }
        public string udf_CreatedBy { get; set; }
        public string udf_AssignedTo { get; set; }
        public string udf_ActivatedBy { get; set; }
        public string udf_ResolvedBy { get; set; }
        public string udf_ClosedBy { get; set; }
        public string udf_Owner { get; set; }
        public Nullable<int> udf_ConnectionID { get; set; }
        public string Risk { get; set; }
        public string ReproSteps { get; set; }
        public Nullable<bool> udf_IsActive { get; set; }
        public string Description { get; set; }
        public string AcceptanceCriteria { get; set; }
        public Nullable<long> PWIID { get; set; }
        public string udf_TreePath { get; set; }
        public Nullable<System.DateTime> udf_RevisedDate { get; set; }
    
        public virtual Connection Connection { get; set; }
    }
}
